// Code generated by "stringer -type=EnrollmentStatus --trimprefix EnrollmentStatus"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EnrollmentStatusPotential-0]
	_ = x[EnrollmentStatusEnrolled-1]
	_ = x[EnrollmentStatusNonPotential-2]
	_ = x[EnrollmentStatusLOA-3]
	_ = x[EnrollmentStatusGraduated-4]
	_ = x[EnrollmentStatusWithdraw-5]
}

const _EnrollmentStatus_name = "PotentialEnrolledNonPotentialLOAGraduatedWithdraw"

var _EnrollmentStatus_index = [...]uint8{0, 9, 17, 29, 32, 41, 49}

func (i EnrollmentStatus) String() string {
	if i < 0 || i >= EnrollmentStatus(len(_EnrollmentStatus_index)-1) {
		return "EnrollmentStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EnrollmentStatus_name[_EnrollmentStatus_index[i]:_EnrollmentStatus_index[i+1]]
}
